language: generic
sudo: required
service:
    - docker

before_install:
    - docker build -t colbyhemond/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true colbyhemond/docker-react npm run test